"""empty message

Revision ID: 769086df7bef
Revises: 40dc1cee0fa5
Create Date: 2022-09-07 15:06:12.116875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769086df7bef'
down_revision = '40dc1cee0fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytul', sa.String(length=64), nullable=True),
    sa.Column('tresc', sa.String(length=800), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
