"""empty message

Revision ID: f08a4e946b4b
Revises: 80aec7e67365
Create Date: 2022-09-09 12:15:53.970447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08a4e946b4b'
down_revision = '80aec7e67365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('przedmiot', sa.String(length=64), nullable=True),
    sa.Column('ocena', sa.String(length=64), nullable=True),
    sa.Column('uczen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uczen'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocena')
    # ### end Alembic commands ###
